version: '3.8'
services:
  api:
    container_name: veloura-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "4300:4300"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - api_node_modules:/app/node_modules
    env_file: .env
    depends_on:
      - veloura-postgres
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000

  veloura-postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: veloura
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  api_node_modules:
  postgres_data:
